max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
fn_args_layout = "Tall"
edition = "2018"
merge_derives = true
use_field_init_shorthand = true

# https://rust-lang.github.io/rustfmt/
# merge_imports = true
