# The address of the game server's XML-RPC port, f.e. "127.0.0.1:5000".
# 
# A game server will listen on the port 5000 by default, where each
# additional instance will use 5001, 5002, etc. A game client
# will also reserve a port, which is relevant for development:
# if you start the game first, the server will listen at port 5001.
# 
# It is also possible to select a specific port, using the `<xmlrpc_port>`
# setting in the server config.
rpc_address = "127.0.0.1:5000"

# The "SuperAdmin" credentials defined in the `<authorization_levels>` config
# in `/UserData/Config/*.txt`.
rpc_login = "SuperAdmin"
rpc_password = "SuperAdmin"

# Connection configuration parsed from libpq-style connection strings, f.e.
# `host=127.0.0.1 port=5432 user=postgres password=123 connect_timeout=10`.
# see also: https://www.postgresql.org/docs/9.3/libpq-connect.html#LIBPQ-CONNSTRING
postgres_connection = "host=127.0.0.1 user=postgres password=123"

# List of player logins that can execute (super) admin commands.
# You should only add people that you trust as super admins, since
# they have the ability to delete players, maps and records from the
# database.
super_admin_whitelist = ["admin1", "admin2"]
admin_whitelist = ["admin3", "admin4"]

# To calculate the time limit of a map, this factor is applied to either the
# author time or the top record.
timelimit_factor = 10

# The maximum time limit in seconds.
timelimit_max_secs = 900

# The minimum time limit in seconds.
timelimit_min_secs = 300

# The time spent on a map after the race ends in seconds.
# Overrides the S_ChatTime mode setting.
# This should be long enough to allow for widget interaction after a race.
# Votes during the outro will be open for two thirds of this value.
outro_duration_secs = 20
